### ISSUE TITLE
Cannot find binary during cargo test in CI

### ISSUE THREAD

**Issue by joepio** [assert-rs/assert_cmd#131]
Hi there! Thanks for creating this. The `cargo_bin` command works great locally, but when I run this in my CI on github [actions](https://github.com/joepio/atomic-data-rust/runs/3321222416?check_suite_focus=true), it seems like the binary in `target/debug/appname` cannot be found. 

```
thread 'test::get_fail' panicked at 'called `Result::unwrap()` on an `Err` value: CargoError { cause: Some(NotFoundError { path: "/home/runner/work/atomic-data-rust/atomic-data-rust/target/debug/atomic-cli" }) }', cli/src/main.rs:330:69
```

**Comment by epage** [comment]
It only works from tests in the `tests/` folder (ie black box / "integration" tests) and not from `src/` (ie white box / "unit" tests).

See [limitations](https://docs.rs/assert_cmd/2.0.0/assert_cmd/cargo/index.html#limitations)

The only reason its working locally is because it is using the binary from your last build/test run and not the current one.

**Comment by joepio** [comment]
Thanks, that fixed it!
